name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test NS tools
      run: cd ns && go test -v ./...

    - name: Test NS3
      run: cd ns/v3 && go test -v ./...

    - name: Test NS4
      run: cd ns/v4 && go test -v ./...

    - name: Test Examples
      run: cd examples && go test -v ./...

    - name: Test EUD
      run: cd eud/v171 && go test -v ./...
