name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test NS tools
      run: go test -v ./ns/...

    - name: Test NS3
      run: go test -v ./ns/v3/...

    - name: Test NS4
      run: go test -v ./ns/v4/...

    - name: Test Examples
      run: go test -v ./examples/...

    - name: Test EUD
      run: go test -v ./eud/v171/...
