name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test-tools:
    name: Test NS tools
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache-dependency-path: ns/go.sum
    - name: Test
      run: cd ns && go test -v ./...

  test-ns3:
    name: Test NS3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: ns/v3/go.sum
      - name: Test
        run: cd ns/v3 && go test -v ./...

  test-ns4:
    name: Test NS4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: ns/v4/go.sum
      - name: Test
        run: cd ns/v4 && go test -v ./...

  test-eud:
    name: Test EUD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: eud/v171/go.sum
      - name: Test
        run: cd eud/v171 && go test -v ./...
